### ISSUE TITLE
Te adicionar nas minhas redes sociais para estudar mais sobre o git e github.

### ISSUE THREAD

**Issue by MellonFive** [sogustavoricardo/studying-git#1]
Opa tudo bem? Queria te add nas minhas redes sociais para estudar mais sobre o git e github se for possível.
Obrigado, amigo! :D

**Comment by sogustavoricardo** [comment]
Oi amigo, bom dia!! Tenho minha conta pessoal do instagram:
@_gustavoricardo, mas não posto nada sobre dev lá :/. Se quiser um lugar
legal pra estar sempre trocando uma ideia sobre programação e afins, entra
nesse servidor: https: //discord.com/invite/pzRrsEgHpn. Tem sempre um
pessoal muito massa por lá falando sobre programação e algumas salas só
para tirar dúvida!!

Em sáb., 27 de fev. de 2021 às 15:33, Felipe Mellão <
notifications@github.com> escreveu:

**Comment by MellonFive** [comment]
Ah beleza amigo. Nesse servidor eu já estou dentro faz tempo! ahushushauhasu Me procura por Mellon Five e tenta me dar um oi pra gente trocar ideia. Falou! :D
